### PR TITLE
Run in browser without crashing, fixes #23

### LINKED ISSUE #23: Example app fails to load in browser because `window.api` is `undefined`
## Expected:

Following the set-up instructions, the demo app should run in both Electron and the browser.

## Actual:

Page loads fine in Electron, but errors in Firefox with `Uncaught (in promise) TypeError: window.api is undefined`.

There is also a preceding error from SvelteKit `[HMR][Svelte] Unrecoverable HMR error in <Index>: next update will trigger a full reload`.

Produced error in both Chromium, Firefox on Linux (Pop!_OS 21.10).

## Problem code?

This looks like where the error is coming from, I would raise a PR but I'm unfamiliar with both SvelteKit and Electron. Hopefully the below investigation helps.

```ts
// src/routes/index.svelte

import { browser } from '$app/env';

let desktop: string;

if (browser) {
  window.api.receive('from-main', (data: any) => {
	  desktop = `Received Message "${data}" from Electron`;
	  console.log(desktop);
  });
}
```

## Screenshots

image

image

### PR DESCRIPTION
**Pull request by oscarhermoso**
Fixes #23

### CODE REVIEW

File: src/lib/Counter.svelte [hunk 1]
```diff
@@ -2,17 +2,21 @@
...
 	const count = getStore(id, 0);
 
 	const handleClick = () => {
 		$count += 1;
-		window.api.send('to-main', $count);
 	};
+
+	if (window.electron) {
+		count.subscribe((c) => window.electron.send('to-main', c));
+	}
```
Comment (ghostdevv) [inline src/lib/Counter.svelte:15]: This should fix the unsub issue

```html
$: if (window.electron) {
    window.electron.send('to-main', $count)
}
```

**Review by ghostdevv — CHANGES_REQUESTED** [review]

File: src/lib/Counter.svelte (hunk 1 above)
Comment (oscarhermoso) [reply src/lib/Counter.svelte:15]: @ghostdevv 

Sorry for the slow reply, have been busy. Happy to implement your change, but there is a slight difference between subscribing with `$: ` and `.subscribe()`.

https://svelte.dev/repl/d595a50133a64f52936a66b9b645a685?version=3.47.0

I can either implement the `$: ` as you suggested, which is definitely cleaner, or I can keep using the more accurate `.subscribe()`, and fix the unsub issue by importing `onDestroy`? What would you prefer?

Comment (ghostdevv) [reply src/lib/Counter.svelte:15]: From looking at the compiled output the reason is that since the two statements in doubleUpdate are directly next to each other svelte will not have processed the dom updates by the time the second statement is ran so it will only know about the final change

I don't see this being an issue myself but if you have a case where it is then I would be interested to see it

Comment (oscarhermoso) [reply src/lib/Counter.svelte]: Yeah, you're right - I've amended my PR implementing your initial suggestion :slightly_smiling_face:

**Review by ghostdevv — APPROVED** [review]

**Comment by ghostdevv** [comment]
Ty!
